#Output list of dirs (result) from parent dir (curdir)
MACRO(SUBDIRLIST result curdir recurse) 
  IF(${recurse})
    FILE(GLOB_RECURSE children LIST_DIRECTORIES true RELATIVE ${curdir} ${curdir}/*)
  ELSE()
    FILE(GLOB children LIST_DIRECTORIES true RELATIVE ${curdir} ${curdir}/*)
  ENDIF()
  SET(dirlist "")
  FOREACH(child ${children})
    IF(IS_DIRECTORY ${curdir}/${child})
      LIST(APPEND dirlist ${child})
    ENDIF()
  ENDFOREACH()
  SET(${result} ${dirlist})
ENDMACRO()